export const QUESTIONS = [
  {
    category: "history",
    id: "622a1c3c7cc59eab6f95190f",
    correctAnswer: "Marco Polo",
    incorrectAnswers: [
      "Christopher Columbus",
      "Ferdinand Magellan",
      "Francis Drake",
    ],
    question: {
      text: "What explorer landed in China and reached Kublai Khan's court in 1275?",
    },
    tags: ["exploration", "people", "middle_ages", "medieval", "history"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "geography",
    id: "622a1c357cc59eab6f94ffc2",
    correctAnswer: "Agra",
    incorrectAnswers: ["Mumbai", "Kolkata", "Chennai"],
    question: {
      text: "In Which Indian City Is The Taj Mahal",
    },
    tags: ["india", "tourist_attractions", "geography"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "film_and_tv",
    id: "624dba4bde6018633d31f6be",
    correctAnswer: "Tina Turner",
    incorrectAnswers: ["Duran Duran", "Nancy Sinatra", "Sam Smith"],
    question: {
      text: "Who performed the theme song to the James Bond film GoldenEye?",
    },
    tags: ["james_bond", "film", "soundtracks", "film_and_tv"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "film_and_tv",
    id: "622a1c367cc59eab6f950398",
    correctAnswer: "David Bowie",
    incorrectAnswers: ["Michael Jackson", "Ringo Starr", "Elvis Presley"],
    question: {
      text: "Which Singer Starred In The Title Role Of The Film 'Merry Christmas Mr Lawrence''?",
    },
    tags: ["film_and_tv"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "history",
    id: "622a1c3c7cc59eab6f95199d",
    correctAnswer: "Tutankhamen's Tomb",
    incorrectAnswers: [
      "The Fountain of Youth",
      "The Turin Shroud",
      "Mount Everest",
    ],
    question: {
      text: "What did Sir Howard Carter discover in 1922?",
    },
    tags: ["history"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "food_and_drink",
    id: "624c605b50d1a5e051325a55",
    correctAnswer: "Belgium",
    incorrectAnswers: ["Japan", "Bahrain", "Laos"],
    question: {
      text: "Moules-Frites is a dish that is most associated with which part of the world?",
    },
    tags: ["food", "food_and_drink"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "film_and_tv",
    id: "622a1c347cc59eab6f94f90c",
    correctAnswer: "The Lord of the Rings",
    incorrectAnswers: ["The Searchers", "Ghost", "My Favorite Year"],
    question: {
      text: "Which film contains the character 'Gollum'?",
    },
    tags: ["fictitious_characters", "film", "general_knowledge", "film_and_tv"],
    type: "text_choice",
    difficulty: "easy",
    regions: [],
    isNiche: false,
  },
  {
    category: "geography",
    id: "622a1c357cc59eab6f94fdef",
    correctAnswer: "Tropic of Capricorn",
    incorrectAnswers: [
      "Tropic of Cancer",
      "Tropic of Virgo",
      "Tropic of Gemini",
    ],
    question: {
      text: "Which tropic passes through Australia?",
    },
    tags: ["australia", "geography"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "science",
    id: "6243356bcfaae40c129614a6",
    correctAnswer: "A Larva",
    incorrectAnswers: ["An Elver", "A Kitten", "An Owlet"],
    question: {
      text: "What is the word for a young termite?",
    },
    tags: ["science"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "arts_and_literature",
    id: "622a1c397cc59eab6f950f50",
    correctAnswer: "Jules Verne",
    incorrectAnswers: [
      "Victor Hugo",
      "Alphonse Daudet",
      "Edgar Rice Burroughs",
    ],
    question: {
      text: "Which author wrote 'Around the World in Eighty Days'?",
    },
    tags: ["arts_and_literature"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "sport_and_leisure",
    id: "6242e84fa22452794eaef210",
    correctAnswer: "The Sky Blues",
    incorrectAnswers: ["The Swans", "The Gunners", "Cottagers"],
    question: {
      text: "What is the nickname of the English football team Coventry City?",
    },
    tags: ["sport"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "film_and_tv",
    id: "622a1c367cc59eab6f9501fd",
    correctAnswer: "Quentin Tarantino",
    incorrectAnswers: ["Steven Spielberg", "Woody Allen", "Martin Scorsese"],
    question: {
      text: "Which director directed Inglourious Basterds?",
    },
    tags: ["film_and_tv"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "geography",
    id: "622a1c357cc59eab6f94ffe4",
    correctAnswer: "Budapest",
    incorrectAnswers: ["Pécs", "Prague", "Salzburg"],
    question: {
      text: "What is the capital of Hungary? ",
    },
    tags: ["capital_cities", "europe", "geography"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "music",
    id: "625063abe12f6dec240bdf79",
    correctAnswer: "Toni Basil",
    incorrectAnswers: ["Wild Cherry", "Edwyn Collins", "Terry Jacks"],
    question: {
      text: "'Mickey' was a one hit wonder in 1982 by which artist?",
    },
    tags: ["songs", "one_hit_wonders"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "science",
    id: "648889175dba6c873ef650e1",
    correctAnswer: "10",
    incorrectAnswers: ["1", "2", "0"],
    question: {
      text: "An earthquake with a magnitude of 8 on the Richter scale has waves that are how many times larger than one with a magnitude of 7?",
    },
    tags: ["numbers", "geology", "science", "geography", "natural_disasters"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "society_and_culture",
    id: "622a1c367cc59eab6f950105",
    correctAnswer: "John",
    incorrectAnswers: ["Matthew", "Mark", "Luke"],
    question: {
      text: "Who is referred to in the New Testament as 'the disciple Jesus loved'?",
    },
    tags: ["society_and_culture"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "arts_and_literature",
    id: "622a1c3b7cc59eab6f9513bd",
    correctAnswer: "Little Women",
    incorrectAnswers: ["Buddenbrooks", "David Copperfield", "Jane Eyre"],
    question: {
      text: "In which book does 'Amy March' appear?",
    },
    tags: ["arts_and_literature"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "society_and_culture",
    id: "6262af894b176d54800e3dce",
    correctAnswer: "Not Safe For Work",
    incorrectAnswers: [
      "Nice Suckers Finish Worst",
      "Now, Salt For Weeks",
      "No Situation For Wheels",
    ],
    question: {
      text: "What do the letters 'NSFW' mean on internet chats?",
    },
    tags: ["the_internet", "initials"],
    type: "text_choice",
    difficulty: "easy",
    regions: [],
    isNiche: false,
  },
  {
    category: "music",
    id: "622a1c347cc59eab6f94fb88",
    correctAnswer: '"Respect" by Aretha Franklin',
    incorrectAnswers: [
      '"Baby Got Back" by Sir Mix-a-Lot',
      '"Pepper" by Butthole Surfers',
      '"Carry On Wayward Son" by Kansas',
    ],
    question: {
      text: 'Which song begins with the lyrics: "What you want, baby, I got it!"?',
    },
    tags: ["songs", "lyrics", "general_knowledge", "music"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "music",
    id: "622a1c397cc59eab6f950cc4",
    correctAnswer: "Queen",
    incorrectAnswers: ["Level 42", "Deep Purple", "Feeder"],
    question: {
      text: "Which British rock band released the song 'The Show Must Go On'?",
    },
    tags: ["music"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "geography",
    id: "623b57e6fd6c701a92118386",
    correctAnswer: "USA",
    incorrectAnswers: ["Brazil", "Spain", "The UK"],
    question: {
      text: "In which country would you find the Statue of Liberty?",
    },
    tags: ["geography"],
    type: "text_choice",
    difficulty: "easy",
    regions: [],
    isNiche: false,
  },
  {
    category: "food_and_drink",
    id: "6462628cab138b829b81ea30",
    correctAnswer: "Corned beef",
    incorrectAnswers: ["Pastrami", "Roast beef", "Ham"],
    question: {
      text: "What type of meat is found in a Reuben sandwich?",
    },
    tags: ["sandwiches", "meat", "food", "food_and_drink"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "science",
    id: "622a1c3f7cc59eab6f9523e4",
    correctAnswer: "Kangaroo",
    incorrectAnswers: ["Squirrel", "Crocodile", "Cow"],
    question: {
      text: "A 'Boomer\" Is The Male Of Which Animal?",
    },
    tags: ["animals", "science"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "music",
    id: "622a1c347cc59eab6f94fbb2",
    correctAnswer: '"Comfortably Numb" by Pink Floyd',
    incorrectAnswers: [
      '"Rapper\'s Delight" by Sugarhill Gang',
      '"Welcome to the Black Parade" by My Chemical Romance',
      '"Baby Got Back" by Sir Mix-a-Lot',
    ],
    question: {
      text: 'Which song begins with the lyrics: "Hello? Is there anybody in there?"?',
    },
    tags: ["songs", "lyrics", "music"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "sport_and_leisure",
    id: "622a1c367cc59eab6f950027",
    correctAnswer: "Golf",
    incorrectAnswers: ["Tennis", "Cricket", "Rugby"],
    question: {
      text: "With what sport is Jack Nicklaus associated?",
    },
    tags: ["people", "general_knowledge", "sport"],
    type: "text_choice",
    difficulty: "easy",
    regions: [],
    isNiche: false,
  },
  {
    category: "arts_and_literature",
    id: "622a1c367cc59eab6f9501cc",
    correctAnswer: "Neuromancer",
    incorrectAnswers: ["Altered Carbon", "We", "The Handmaid's Tale"],
    question: {
      text: "Which piece of written work starts with the line 'The sky above the port was the color of television, tuned to a dead channel.'?",
    },
    tags: ["arts_and_literature"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "music",
    id: "622a1c357cc59eab6f94fd4a",
    correctAnswer: "Guns N Roses",
    incorrectAnswers: ["Sex Pistols", "The Ramones", "The Clash"],
    question: {
      text: 'With Which Rock Band Does "Slash" Play Guitar?',
    },
    tags: ["people", "general_knowledge", "music"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "geography",
    id: "6471bcf37206d7c314606f5d",
    correctAnswer: "New Zealand",
    incorrectAnswers: ["Australia", "Indonesia", "Philippines"],
    question: {
      text: "In which country is Lake Taupo?",
    },
    tags: ["bodies_of_water", "lakes", "geography"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "film_and_tv",
    id: "622a1c357cc59eab6f94fd76",
    correctAnswer: "Elton John",
    incorrectAnswers: ["Paul McCartney", "Paul Simon", "Michael Jackson"],
    question: {
      text: "Who Wrote The Music To The 1994 Movie “The Lion King”",
    },
    tags: ["film", "disney", "soundtracks", "1990's", "film_and_tv"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "film_and_tv",
    id: "625698e39da29df7b05f72a4",
    correctAnswer: "Michael Douglas",
    incorrectAnswers: [
      "Benedict Cumberbatch",
      "Tom Hiddleston",
      "Stellan Skarsgård",
    ],
    question: {
      text: "Which actor plays the role of Dr. Hank Pym in the Marvel Cinematic Universe?",
    },
    tags: ["mcu", "film", "acting", "marvel", "comics", "film_and_tv"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "geography",
    id: "64626214ab138b829b81e9ba",
    correctAnswer: "Zurich",
    incorrectAnswers: ["Bern", "Geneva", "Basel"],
    question: {
      text: "What is Switzerland's most populous city?",
    },
    tags: ["cities", "switzerland", "europe", "geography"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "society_and_culture",
    id: "622a1c3c7cc59eab6f951ad3",
    correctAnswer: "Capricorn",
    incorrectAnswers: ["Gemini", "Aries", "Scorpio"],
    question: {
      text: "What star sign would you be if you were born on Christmas Day?",
    },
    tags: ["christmas", "symbols", "society_and_culture"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "food_and_drink",
    id: "64626208ab138b829b81e9a1",
    correctAnswer: "last call",
    incorrectAnswers: ["closing time", "final chugs", "lights up"],
    question: {
      text: "What is the 2-word final warning to order drinks before the bar closes?",
    },
    tags: [
      "alcohol",
      "drink",
      "food_and_drink",
      "society_and_culture",
      "phrases",
    ],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "food_and_drink",
    id: "624ab0c9348a461bfc670699",
    correctAnswer: "India",
    incorrectAnswers: ["Southeast Asia", "China", "Central Asia"],
    question: {
      text: "From which part of the world do limes originally come from?",
    },
    tags: ["food_and_drink"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "science",
    id: "622a1c377cc59eab6f9504e9",
    correctAnswer:
      "diseases and the care of newborn infants; a branch of pediatrics/paediatrics",
    incorrectAnswers: [
      "the theory of monads",
      "numbers",
      "movement in relation to human anatomy",
    ],
    question: {
      text: "What is Neonatology the study of?",
    },
    tags: ["words", "science"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "society_and_culture",
    id: "6293ec9f7f41d6338b96eefe",
    correctAnswer: "Voltaire",
    incorrectAnswers: ["Euclid", "Wilhelm Conrad Roentgen", "Mencius"],
    question: {
      text: "Which influential historical person was a key figure of the European Enlightenment whose satirical writings played a role in the French Revolution?",
    },
    tags: ["people", "history", "society_and_culture"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "food_and_drink",
    id: "627164661ba117625baac95d",
    correctAnswer: "Kumis",
    incorrectAnswers: ["Sombai", "Guaro", "Mama Juana"],
    question: {
      text: "Which of these is a popular drink in Mongolia?",
    },
    tags: ["drink", "alcohol"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "geography",
    id: "6260302a4b176d54800e3d11",
    correctAnswer: "Chisinau",
    incorrectAnswers: ["Vienna", "Cologne", "Geneva"],
    question: {
      text: "Which of these cities is in Moldova?",
    },
    tags: ["cities", "europe", "geography"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "geography",
    id: "623384dc62eaad73716a8c36",
    correctAnswer: "Wellington, New Zealand ",
    incorrectAnswers: [
      "Canberra, Australia",
      "Cape Town, South Africa",
      "Santiago, Chile",
    ],
    question: {
      text: "What is the world's most southerly capital?",
    },
    tags: ["capital_cities", "records", "places", "geography"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "science",
    id: "622a1c3a7cc59eab6f951061",
    correctAnswer: "The Structure of Cells",
    incorrectAnswers: ["Blood", "Code-Breaking", "Cloud Formations"],
    question: {
      text: "What is Cytology the study of?",
    },
    tags: ["science"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "general_knowledge",
    id: "622a1c377cc59eab6f950446",
    correctAnswer: "Scorpio",
    incorrectAnswers: ["Aries", "Gemini", "Cancer"],
    question: {
      text: "If you were born on Halloween, what star sign would you be",
    },
    tags: ["halloween", "general_knowledge"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "arts_and_literature",
    id: "64720648222d3df382f0c86b",
    correctAnswer: "War and Peace",
    incorrectAnswers: [
      "Anna Karenina",
      "The Brothers Karamazov",
      "Crime and Punishment",
    ],
    question: {
      text: "Which novel by Leo Tolstoy was published in separate parts from 1865 to 1869?",
    },
    tags: ["arts_and_literature", "literature", "novels", "classic_novels"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "film_and_tv",
    id: "622a1c347cc59eab6f94fb51",
    correctAnswer: "Rocky",
    incorrectAnswers: ["All the President's Men", "Bound for Glory", "Network"],
    question: {
      text: "Which film won the Academy Award for Best Picture in 1976?",
    },
    tags: ["academy_awards", "film", "film_and_tv"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "music",
    id: "622a1c387cc59eab6f950b9c",
    correctAnswer: "Wings",
    incorrectAnswers: ["Level 42", "Deep Purple", "The Chemical Brothers"],
    question: {
      text: "Which British–American rock band led by Paul McCartney released the album 'Band on the Run'?",
    },
    tags: ["music"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "society_and_culture",
    id: "63b069324799123c67712f61",
    correctAnswer: "Mao suit",
    incorrectAnswers: ["Kurta", "Sherwani", "Nehru Jacket"],
    question: {
      text: "Which of these is a style of tunic suit worn in China?",
    },
    tags: ["society_and_culture", "china", "fashion"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "science",
    id: "622a1c3a7cc59eab6f950fc9",
    correctAnswer: "Dmitri Mendeleev",
    incorrectAnswers: ["Michael Faraday", "James Clerk Maxwell", "Marie Curie"],
    question: {
      text: "Who devised the periodic table of elements?",
    },
    tags: ["chemistry", "people", "science"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "music",
    id: "622a1c357cc59eab6f94feb1",
    correctAnswer: "Beyoncé",
    incorrectAnswers: ["Madonna", "Drake", "Nicki Minaj"],
    question: {
      text: "Who released the song 'Run the World'?",
    },
    tags: ["songs", "2010's", "musicians", "music"],
    type: "text_choice",
    difficulty: "easy",
    regions: [],
    isNiche: false,
  },
  {
    category: "music",
    id: "622a1c357cc59eab6f94ff43",
    correctAnswer: "Michael Jackson",
    incorrectAnswers: ["Nicki Minaj", "Neil Young", "Eric Clapton"],
    question: {
      text: "Which American singer released the song 'Bad'?",
    },
    tags: ["songs", "general_knowledge", "music"],
    type: "text_choice",
    difficulty: "easy",
    regions: [],
    isNiche: false,
  },
  {
    category: "general_knowledge",
    id: "64720cd33bbb58c31f411cc1",
    correctAnswer: "Heteronyms",
    incorrectAnswers: ["Homonyms", "Synonyms", "Antonyms"],
    question: {
      text: "Which term refers to words that are spelled the same but have different sounds and neanings?",
    },
    tags: ["words", "language", "general_knowledge"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
  {
    category: "film_and_tv",
    id: "645f94b4541c4d4fc8cf2e53",
    correctAnswer: "The Deer Hunter",
    incorrectAnswers: ["Coming Home", "Apocalypse Now", "Platoon"],
    question: {
      text: "What 1978 movie saw Robert De Niro battling post-Vietnam stress?",
    },
    tags: ["film", "film_and_tv", "vietnam_war", "acting"],
    type: "text_choice",
    difficulty: "medium",
    regions: [],
    isNiche: false,
  },
];
